<?php
$products = [
    [
        'id' => 'shg-zinc',
        'slug' => 'shg-zinc-ingots',
        'name' => 'SHG Zinc Ingots',
        'short_name' => 'SHG Zinc',
        'grade' => '99.995% Zn',
        'category' => 'Primary Metals',
        'tagline' => 'High purity Special High Grade zinc ingots',
        'image' => 'assets/images/products/Zinc Ingot.png',
        'thumb' => 'assets/images/products/shg-zinc.svg',
        'lab_report_image' => 'assets/images/lab-reports/Zinc Ingot.png',
        'description' => 'Imported SHG (Special High Grade) zinc ingots with minimum 99.995% zinc content, suitable for galvanizing, die-casting and alloy production.',
        'long_desc' => 'BhattiZinc imports premium SHG zinc ingots (99.995% Zn) from trusted international suppliers, ensuring consistent LME-grade purity and full Certificates of Analysis with every shipment.',
        'purity' => '99.995% min',
        'form' => '25 kg ingots, Jumbo Blocks',
        'weight' => '25 kg per ingot',
        'standard' => 'LME Grade / Industry Specifications',
        'applications' => ['Hot-Dip Galvanizing','Zinc Alloy Manufacturing','Brass Industry','Die Casting','Chemical Processing'],
        'specs' => ['Zn' => '99.995% min'],
        'packaging' => 'Wooden pallets, shrink-wrapped. 18–20 MT per 20ft container.',
        'certificates' => ['LME Registered','ISO 9001:2015'],
        'featured' => true,
        'hero_order' => 1,
    ],
    [
        'id' => 'secondary-zinc',
        'slug' => 'secondary-zinc-ingots',
        'name' => 'Secondary Zinc Ingots',
        'short_name' => 'Secondary Zinc',
        'grade' => '95–98% Zn',
        'category' => 'Secondary Metals',
        'tagline' => 'Economical recycled zinc ingots',
        'image' => 'assets/images/products/secondry-zinc-ingot.png',
        'thumb' => 'assets/images/products/zinc-ingots.svg',
        'lab_report_image' => 'assets/images/lab-reports/secondary-zinc-ingots.jpg',
        'description' => 'Secondary zinc ingots produced through recycling and smelting with typical zinc content of 95–98%, offering a cost-effective raw material for industrial use.',
        'long_desc' => 'Our secondary zinc ingots are manufactured using advanced recycling processes to deliver consistent metallurgical properties and competitive pricing for alloyers, foundries and galvanizers.',
        'purity' => '95–98% Zn',
        'form' => 'Ingots / Blocks',
        'weight' => 'Varies per customer requirement',
        'standard' => 'Export Quality / Industry Standards',
        'applications' => ['Secondary Zinc Manufacturing','Alloy Production','Galvanizing','Metal Recycling'],
        'specs' => ['Zn' => '95–98% typical'],
        'packaging' => 'Palletised bundles. Bulk shipments available.',
        'certificates' => ['ISO 9001:2015'],
        'featured' => false,
        'hero_order' => 0,
    ],
    [
        'id' => 'zinc-alloy',
        'slug' => 'zinc-alloy-92-94',
        'name' => 'Zinc Alloy',
        'short_name' => 'Zinc Alloy',
        'grade' => '92–94% Zn',
        'category' => 'Alloys',
        'tagline' => 'Premium zinc alloys for die casting',
        'image' => 'assets/images/products/zinc-alloy.jpg',
        'thumb' => 'assets/images/products/zinc-alloys.svg',
        'lab_report_image' => 'assets/images/lab-reports/zinc-alloy-92-94.jpg',
        'description' => 'High-quality zinc alloys (92–94% Zn) engineered for die casting, hardware and automotive components.',
        'long_desc' => 'Manufactured to strict quality controls, our zinc alloys deliver excellent casting performance and dimensional stability for industrial applications.',
        'purity' => '92–94% Zn',
        'form' => 'Ingots, Rods, Billets',
        'weight' => '1–25 kg',
        'standard' => 'ASTM / EN where applicable',
        'applications' => ['Die Casting','Hardware Manufacturing','Automotive Components','Electrical Parts','Engineering Products'],
        'specs' => ['Zn' => '92–94% typical'],
        'packaging' => 'Timber pallets. Containerised shipments.',
        'certificates' => ['ISO 9001:2015'],
        'featured' => false,
        'hero_order' => 3,
    ],
    [
        'id' => 'iranian-zinc',
        'slug' => 'iranian-zinc-ingots',
        'name' => 'Iranian Zinc Ingots',
        'short_name' => 'Iranian Zinc',
        'grade' => 'Varies (Standard Export Grades)',
        'category' => 'Imported Metals',
        'tagline' => 'Sourced Iranian zinc ingots for Pakistan markets',
        'image' => 'assets/images/products/Zinc Ingot.png',
        'thumb' => 'assets/images/products/zinc-ingots.svg',
        'lab_report_image' => 'assets/images/lab-reports/iranian-zinc-ingots.jpg',
        'description' => 'Imported Iranian zinc ingots supplied reliably for industry in Pakistan, used widely in galvanizing and alloy production.',
        'long_desc' => 'BhattiZinc imports and distributes Iranian zinc ingots, ensuring dependable availability and timely delivery to industrial customers nationwide.',
        'purity' => 'Per supplied batch',
        'form' => '25 kg ingots / Bulk',
        'weight' => '25 kg per ingot',
        'standard' => 'Export Grade / Customer Specs',
        'applications' => ['Hot-Dip Galvanizing','Brass Manufacturing','Zinc Alloy Production','Foundries'],
        'specs' => ['Zn' => 'Per batch specs'],
        'packaging' => 'Standard export packaging.',
        'certificates' => ['Export Documentation'],
        'featured' => false,
        'hero_order' => 0,
    ],
    [
        'id' => 'zinc-oxide',
        'slug' => 'zinc-oxide-99-99',
        'name' => 'Zinc Oxide',
        'short_name' => 'Zinc Oxide',
        'grade' => '99.99% ZnO',
        'category' => 'Chemical Products',
        'tagline' => 'Premium zinc oxide for industrial use',
        'image' => 'assets/images/products/Bhatti-Zinc zincOxide Apperance.webp',
        'thumb' => 'assets/images/products/zinc-oxide.svg',
        'lab_report_image' => 'assets/images/lab-reports/zinc-oxide-99-99.jpg',
        'description' => 'Premium-grade Zinc Oxide (99.99% purity) for rubber, ceramics, coatings and chemical industries.',
        'long_desc' => 'Manufactured and quality-controlled to deliver high whiteness, chemical stability and consistent performance across industrial applications.',
        'purity' => '99.99% ZnO',
        'form' => 'Fine Powder',
        'weight' => '25 kg bags / Big bags',
        'standard' => 'ISO / Industry Grades',
        'applications' => ['Rubber','Ceramics','Paints & Coatings','Chemicals','Pharmaceuticals','Animal Feed'],
        'specs' => ['ZnO' => '99.99% min'],
        'packaging' => '25 kg paper bags on pallets. 20 MT per 20ft container.',
        'certificates' => ['ISO 9001:2015','REACH Compliant'],
        'featured' => true,
        'hero_order' => 2,
    ],
    
    [
        'id' => 'zinc-ash-high',
        'slug' => 'zinc-ash-65-70',
        'name' => 'Zinc Ash',
        'short_name' => 'Zinc Ash',
        'grade' => '65–70% Zn',
        'category' => 'Recycling & By-Products',
        'tagline' => 'Recovered zinc ash for metal recovery',
        'image' => 'assets/images/products/ZincAshFine.jpg',
        'thumb' => 'assets/images/products/zinc-ash.svg',
        'lab_report_image' => 'assets/images/lab-reports/zinc-ash-65-70.jpg',
        'description' => 'High-grade zinc ash recovered from processing operations, containing 65–70% zinc suitable for recovery and recycling.',
        'long_desc' => 'A sustainable by-product with high zinc recovery value used by recyclers and smelters to reclaim metallic zinc.',
        'purity' => '65–70% Zn',
        'form' => 'Loose / Bulk',
        'weight' => 'Bulk truck / container',
        'standard' => 'Recycling Grade',
        'applications' => ['Zinc Recovery','Metal Recycling'],
        'specs' => ['Zn' => '65–70% typical'],
        'packaging' => 'Bulk / Big bags.',
        'certificates' => ['Export Quality'],
        'featured' => true,
        'hero_order' => 4,
    ],
    [
        'id' => 'zinc-ash-low',
        'slug' => 'zinc-skimming-30-40',
        'name' => 'Zinc Skimming',
        'short_name' => 'Zinc Skimming',
        'grade' => '30–40% Zn',
        'category' => 'Recycling & By-Products',
        'tagline' => 'Cost-effective zinc skimming for recovery operations',
        'image' => 'assets/images/products/zinc-skimming.jpeg',
        'thumb' => 'assets/images/products/zinc-dust.svg',
        'lab_report_image' => 'assets/images/lab-reports/low-grade-zinc-ash-30-40.jpg',
        'description' => 'Zinc skimming suitable for large-scale Zinc recovery processes and recycling operations.',
        'long_desc' => 'Economical raw material for metal recovery plants and recyclers seeking cost-effective feedstock.',
        'purity' => '70–80% Zn',
        'form' => 'Loose / Bulk',
        'weight' => 'Bulk quantities',
        'standard' => 'Recycling Grade',
        'applications' => ['Zinc Recovery','Industrial Recycling'],
        'specs' => ['Zn' => '30–40% typical'],
        'packaging' => 'Bulk shipments / Big bags.',
        'certificates' => ['Export Quality'],
        'featured' => false,
        'hero_order' => 0,
    ],
    [
        'id' => 'apcd-ash',
        'slug' => 'apcd-zinc-ash-50-60',
        'name' => 'APCD Zinc Ash',
        'short_name' => 'APCD Ash',
        'grade' => '50–60% Zn',
        'category' => 'Recycling & By-Products',
        'tagline' => 'Air pollution control dust with recoverable zinc',
        'image' => 'assets/images/products/ZincDust.jpg',
        'thumb' => 'assets/images/products/zinc-dust.svg',
        'lab_report_image' => 'assets/images/lab-reports/apcd-zinc-ash-50-60.jpg',
        'description' => 'Air Pollution Control Dust (steel mill dust) containing 50–60% zinc recovered from air pollution control systems, valuable for recycling.',
        'long_desc' => 'Collected from modern steel mill APC systems, this material is an environmentally sustainable source of zinc for recovery processes.',
        'purity' => '50–60% Zn',
        'form' => 'Dust / Bulk',
        'weight' => 'Bulk shipments',
        'standard' => 'Recycling / Export Grade',
        'applications' => ['Zinc Recovery','Recycling','Metallurgical Use'],
        'specs' => ['Zn' => '50–60% typical'],
        'packaging' => 'Bulk / Big bags.',
        'certificates' => ['Export Quality'],
        'featured' => true,
        'hero_order' => 6,
    ],
    [
        'id' => 'zinc-dross',
        'slug' => 'zinc-dross-94-97',
        'name' => 'Zinc Dross',
        'short_name' => 'Zinc Dross',
        'grade' => '94–97% Zn',
        'category' => 'Recycling & By-Products',
        'tagline' => 'High-grade zinc dross for recovery and alloying',
        'image' => 'assets/images/products/ZincDross.jpg',
        'thumb' => 'assets/images/products/zinc-dust.svg',
        'lab_report_image' => 'assets/images/lab-reports/zinc-dross-94-97.jpg',
        'description' => 'Zinc dross with 94–97% zinc content processed and supplied for recovery and secondary manufacturing.',
        'long_desc' => 'Sourced and processed to retain high zinc value, our dross is used by recovery plants and alloy producers.',
        'purity' => '94–97% Zn',
        'form' => 'Solid / Granular',
        'weight' => 'Per order',
        'standard' => 'Industrial Recovery Grade',
        'applications' => ['Zinc Recovery','Alloy Production','Secondary Manufacturing'],
        'specs' => ['Zn' => '94–97% typical'],
        'packaging' => 'Bulk / Bags as required.',
        'certificates' => ['Export Quality'],
        'featured' => false,
        'hero_order' => 5,
    ],
    [
        'id' => 'die-cast-scrap',
        'slug' => 'zinc-die-cast-scrap',
        'name' => 'Zinc Die Cast Scrap',
        'short_name' => 'Die Cast Scrap',
        'grade' => 'Varies',
        'category' => 'Scrap & Recycling',
        'tagline' => 'Zinc die cast scrap for recycling and remelting',
        'image' => 'assets/images/products/zinc-die-cast.png',
        'thumb' => 'assets/images/products/zinc-dust.svg',
        'lab_report_image' => 'assets/images/lab-reports/zinc-die-cast-scrap.jpg',
        'description' => 'Imported and locally sourced zinc die cast scrap, prepared for recycling and remelting in secondary operations.',
        'long_desc' => 'Carefully sourced, sorted and supplied to meet recycler and smelter requirements for consistent material quality and value.',
        'purity' => 'Varies by source',
        'form' => 'Scrap / Granules',
        'weight' => 'Per order',
        'standard' => 'Industry Scrap Grades',
        'applications' => ['Recycling','Remelting','Secondary Production'],
        'specs' => ['Zn' => 'Varies'],
        'packaging' => 'Bulk / Containers',
        'certificates' => ['Export Documentation'],
        'featured' => false,
        'hero_order' => 0,
    ],
];

$productSeoContent = [
    'shg-zinc-ingots' => [
        'meta_description' => 'Buy SHG zinc ingots 99.995% Zn for hot-dip galvanizing, die casting, brass, alloy production and chemical processing from BhattiZinc Pakistan.',
        'seo_keywords' => ['SHG zinc ingots', '99.995 zinc ingot supplier', 'zinc ingots for galvanizing', 'LME grade zinc', 'zinc ingots Pakistan', 'zinc for die casting'],
        'hero_seo' => [
            'title' => 'SHG Zinc Ingots for Galvanizing, Die Casting and Alloy Production',
            'body' => 'BhattiZinc supplies Special High Grade zinc ingots with 99.995% minimum zinc content for buyers who need clean chemistry, reliable melting behavior and documented quality. This grade is a preferred raw material for hot-dip galvanizing plants, brass makers, zinc alloy producers and die-casting operations that depend on consistent feedstock.',
            'highlights' => ['SHG zinc ingots', '99.995% Zn', 'Hot-dip galvanizing', 'Die casting'],
        ],
        'seo_blog' => [
            'title' => 'Why SHG Zinc Ingots Matter for Galvanizing and Precision Manufacturing',
            'intro' => 'When buyers search for zinc ingots, SHG zinc or LME grade zinc, they are usually trying to reduce production variation. A high-purity ingot gives galvanizers, alloyers and die casters a controlled base metal that supports repeatable results.',
            'sections' => [
                ['heading' => 'A clean base for zinc coating', 'body' => 'Hot-dip galvanizing relies on molten zinc to protect steel from corrosion. SHG zinc ingots help maintain bath quality, support bright coating performance and reduce unwanted impurity buildup during long production runs.'],
                ['heading' => 'Useful across alloy and brass plants', 'body' => 'Manufacturers use 99.995% zinc ingots in brass, zinc alloy and die-casting formulations because the chemistry is easier to adjust. Starting with a cleaner zinc source gives technical teams more control over aluminum, copper and other alloying additions.'],
                ['heading' => 'Documentation buyers should ask for', 'body' => 'For export and industrial procurement, request the Certificate of Analysis, packing details, origin documents and container loading plan. These records help purchasing teams compare SHG zinc suppliers beyond price alone.'],
            ],
            'faq' => [
                ['question' => 'What is SHG zinc used for?', 'answer' => 'SHG zinc is commonly used for galvanizing, zinc alloy production, die casting, brass manufacturing and chemical processing.'],
                ['question' => 'What purity is Special High Grade zinc?', 'answer' => 'SHG zinc is generally specified at 99.995% minimum zinc content.'],
            ],
        ],
    ],
    'secondary-zinc-ingots' => [
        'meta_description' => 'Secondary zinc ingots 95-98% Zn for economical alloy production, galvanizing, foundry use and metal recycling supply chains.',
        'seo_keywords' => ['secondary zinc ingots', 'recycled zinc ingots', '95 98 zinc ingots', 'secondary zinc supplier', 'zinc ingots for recycling', 'cost effective zinc'],
        'hero_seo' => [
            'title' => 'Secondary Zinc Ingots for Cost-Efficient Industrial Production',
            'body' => 'Secondary zinc ingots offer practical value for manufacturers that need usable zinc content with competitive pricing. BhattiZinc supplies recycled zinc ingots for alloy production, foundry work, galvanizing support and secondary manufacturing where balanced cost and dependable material behavior are essential.',
            'highlights' => ['Secondary zinc ingots', '95-98% Zn', 'Recycled zinc', 'Alloy production'],
        ],
        'seo_blog' => [
            'title' => 'How Secondary Zinc Ingots Support Lower-Cost Zinc Manufacturing',
            'intro' => 'Searches for recycled zinc ingots and secondary zinc suppliers are often driven by cost control. The right secondary zinc grade can reduce raw material spend while keeping production suitable for many industrial uses.',
            'sections' => [
                ['heading' => 'Where secondary zinc fits best', 'body' => 'Secondary zinc ingots are used by alloyers, foundries and selected galvanizing operations where the final specification allows recycled feedstock. They are especially useful in blended melts and secondary metal production.'],
                ['heading' => 'Why chemistry still matters', 'body' => 'A lower price only helps when the ingot chemistry is understood. Buyers should compare zinc percentage, iron, lead and other residual elements against the needs of their process.'],
                ['heading' => 'A practical route for circular supply', 'body' => 'Using recycled zinc supports resource efficiency and helps keep valuable zinc in industrial circulation. For many buyers, secondary zinc provides both economic and sustainability benefits.'],
            ],
            'faq' => [
                ['question' => 'Are secondary zinc ingots suitable for alloy making?', 'answer' => 'Yes, secondary zinc ingots are widely used for alloy production when the batch chemistry matches the required specification.'],
                ['question' => 'Why choose recycled zinc ingots?', 'answer' => 'They can lower raw material cost and support circular metal use while still delivering useful zinc content.'],
            ],
        ],
    ],
    'zinc-alloy-92-94' => [
        'meta_description' => 'Zinc alloy 92-94% Zn for die casting, hardware, automotive components, electrical parts and engineering products.',
        'seo_keywords' => ['zinc alloy supplier', 'zinc alloy for die casting', '92 94 zinc alloy', 'zinc alloy ingots', 'automotive zinc alloy', 'hardware zinc alloy'],
        'hero_seo' => [
            'title' => 'Zinc Alloy for Die Casting, Hardware and Automotive Components',
            'body' => 'BhattiZinc zinc alloy is prepared for manufacturers that need strong casting performance, dimensional stability and reliable repeat orders. With 92-94% typical zinc content, it serves die casting, hardware, automotive, electrical and engineering applications where clean melting and consistent alloy behavior matter.',
            'highlights' => ['Zinc alloy', 'Die casting', 'Hardware manufacturing', 'Automotive components'],
        ],
        'seo_blog' => [
            'title' => 'Choosing Zinc Alloy for Die Casting and Industrial Components',
            'intro' => 'Zinc alloy searches usually come from buyers comparing casting performance, strength, surface finish and price. A consistent alloy can make production faster and reduce defects in high-volume component manufacturing.',
            'sections' => [
                ['heading' => 'Why zinc alloys are popular in die casting', 'body' => 'Zinc alloys melt at relatively low temperatures and can produce accurate parts with fine detail. This makes them useful for hardware, brackets, housings, fittings and automotive components.'],
                ['heading' => 'Applications that need repeatability', 'body' => 'Electrical parts, engineering products and decorative hardware often require stable dimensions and clean surfaces. Consistent zinc alloy feedstock helps keep tooling performance predictable.'],
                ['heading' => 'What buyers should verify', 'body' => 'Before ordering zinc alloy ingots, confirm the zinc range, alloying elements, intended casting process, packaging and batch documentation. Matching the alloy to the application is more important than buying by name alone.'],
            ],
            'faq' => [
                ['question' => 'Is zinc alloy good for die casting?', 'answer' => 'Yes, zinc alloy is widely used in die casting because it supports detailed shapes, stable dimensions and efficient production.'],
                ['question' => 'What industries use zinc alloy?', 'answer' => 'Common users include hardware, automotive, electrical, engineering and decorative component manufacturers.'],
            ],
        ],
    ],
    'iranian-zinc-ingots' => [
        'meta_description' => 'Iranian zinc ingots supplied for Pakistan industry, galvanizing, brass manufacturing, foundries and zinc alloy production.',
        'seo_keywords' => ['Iranian zinc ingots', 'zinc ingots Pakistan', 'imported zinc ingots', 'zinc ingot supplier Pakistan', 'zinc for galvanizing', 'zinc for brass'],
        'hero_seo' => [
            'title' => 'Iranian Zinc Ingots for Pakistan Galvanizing and Alloy Markets',
            'body' => 'BhattiZinc sources and distributes Iranian zinc ingots for industrial buyers that need dependable availability, practical pricing and batch documentation. These imported zinc ingots serve hot-dip galvanizing, brass manufacturing, foundries and zinc alloy production across Pakistan.',
            'highlights' => ['Iranian zinc ingots', 'Imported zinc', 'Galvanizing', 'Brass manufacturing'],
        ],
        'seo_blog' => [
            'title' => 'Buying Iranian Zinc Ingots for Industrial Use in Pakistan',
            'intro' => 'Iranian zinc ingots are searched by buyers looking for a steady imported zinc source near Pakistan. The best supplier choice depends on availability, batch chemistry, logistics and clear documentation.',
            'sections' => [
                ['heading' => 'Uses in local manufacturing', 'body' => 'Imported Iranian zinc ingots are used in galvanizing, foundries, brass production and alloy manufacturing. They provide a practical option when buyers need flexible supply and competitive landed cost.'],
                ['heading' => 'Compare batch specifications', 'body' => 'Because supplied grades can vary, buyers should review each Certificate of Analysis before production. Zinc percentage and residual elements should match the intended melt or bath use.'],
                ['heading' => 'Logistics and availability matter', 'body' => 'For Pakistan manufacturers, delivery timing can be as important as price. A supplier with local handling experience can help reduce stock gaps and keep production moving.'],
            ],
            'faq' => [
                ['question' => 'What are Iranian zinc ingots used for?', 'answer' => 'They are commonly used for galvanizing, brass manufacturing, foundries and zinc alloy production.'],
                ['question' => 'Do Iranian zinc ingot grades vary?', 'answer' => 'Yes, buyers should check the batch specification and Certificate of Analysis for each shipment.'],
            ],
        ],
    ],
    'zinc-oxide-99-99' => [
        'meta_description' => 'Premium zinc oxide 99.99% ZnO powder for rubber, ceramics, paints, coatings, chemicals, pharmaceuticals and animal feed applications.',
        'seo_keywords' => ['zinc oxide supplier', '99.99 zinc oxide', 'zinc oxide powder', 'ZnO for rubber', 'zinc oxide for ceramics', 'zinc oxide Pakistan'],
        'hero_seo' => [
            'title' => 'Zinc Oxide Powder for Rubber, Ceramics, Coatings and Chemicals',
            'body' => 'BhattiZinc supplies high-purity zinc oxide powder for industrial buyers who need whiteness, chemical stability and consistent performance. Zinc oxide is widely searched for rubber compounding, ceramic frits, paints, coatings, chemicals, pharmaceuticals and animal feed formulations.',
            'highlights' => ['Zinc oxide powder', '99.99% ZnO', 'Rubber compounding', 'Ceramics and coatings'],
        ],
        'seo_blog' => [
            'title' => 'Industrial Uses of Zinc Oxide Powder and How to Choose a Supplier',
            'intro' => 'Zinc oxide is one of the most searched zinc chemicals because it appears in rubber, ceramics, coatings, feed and chemical manufacturing. Buyers need purity, particle consistency and reliable packing.',
            'sections' => [
                ['heading' => 'Rubber and tire applications', 'body' => 'Zinc oxide is a key material in rubber compounding, where it helps vulcanization systems perform properly. Consistent ZnO quality supports predictable curing and finished product performance.'],
                ['heading' => 'Ceramics, coatings and chemicals', 'body' => 'In ceramics and coatings, zinc oxide can support opacity, stability and functional properties. Chemical producers also use ZnO as a zinc source for downstream zinc compounds.'],
                ['heading' => 'Supplier checks for ZnO buyers', 'body' => 'Ask for purity, whiteness, moisture, packing format and batch documentation. For export markets, SDS, compliance paperwork and palletized packing can reduce receiving delays.'],
            ],
            'faq' => [
                ['question' => 'What is zinc oxide powder used for?', 'answer' => 'Zinc oxide is used in rubber, ceramics, paints, coatings, chemicals, pharmaceuticals and animal feed.'],
                ['question' => 'What does 99.99% ZnO mean?', 'answer' => 'It indicates a high-purity zinc oxide grade with very low impurity levels for demanding industrial applications.'],
            ],
        ],
    ],
    'zinc-sulphate' => [
        'meta_description' => 'Zinc sulphate for fertilizer, agriculture, animal feed, chemical processing, electroplating and industrial zinc compound applications.',
        'seo_keywords' => ['zinc sulphate supplier', 'zinc sulfate', 'zinc sulphate fertilizer', 'zinc sulphate agriculture', 'zinc sulphate animal feed', 'zinc chemicals Pakistan'],
        'hero_seo' => [
            'title' => 'Zinc Sulphate for Agriculture, Feed and Industrial Applications',
            'body' => 'BhattiZinc supplies zinc sulphate for buyers who need a practical zinc chemical for fertilizer blending, agriculture, animal feed, chemical processing and selected industrial uses. Packing, grade and documentation can be aligned with the customer application and shipment requirements.',
            'highlights' => ['Zinc sulphate', 'Agriculture grade', 'Feed and fertilizer', 'Industrial chemical'],
        ],
        'seo_blog' => [
            'title' => 'Zinc Sulphate Supply for Agriculture and Industrial Buyers',
            'intro' => 'Zinc sulphate is used where manufacturers and agricultural buyers need a soluble zinc source with clear grade details, stable packing and dependable supply.',
            'sections' => [
                ['heading' => 'Use in fertilizer and agriculture', 'body' => 'Zinc sulphate is commonly used in fertilizer blends and soil nutrition programs where zinc availability is required. Buyers should match the supplied grade and zinc percentage to the intended application.'],
                ['heading' => 'Industrial and chemical applications', 'body' => 'Chemical processors may use zinc sulphate as a zinc source for downstream compounds, electroplating support and other industrial formulations where batch consistency matters.'],
                ['heading' => 'What buyers should confirm', 'body' => 'Before ordering, confirm the form, zinc content, moisture, packing size, labeling, safety documentation and shipment quantity so the material matches receiving and production needs.'],
            ],
            'faq' => [
                ['question' => 'What is zinc sulphate used for?', 'answer' => 'Zinc sulphate is used in fertilizer, agriculture, animal feed, chemical processing, electroplating and other industrial applications.'],
                ['question' => 'Is zinc sulphate supplied in different grades?', 'answer' => 'Yes, zinc sulphate can be supplied in different forms and grades, so buyers should confirm zinc content, packing and application requirements before ordering.'],
            ],
        ],
    ],
    'zinc-ash-65-70' => [
        'meta_description' => 'Zinc ash 65-70% Zn for zinc recovery, smelting, recycling and secondary zinc production from BhattiZinc.',
        'seo_keywords' => ['zinc ash supplier', '65 70 zinc ash', 'zinc ash for recovery', 'zinc recycling feedstock', 'galvanizing zinc ash', 'zinc ash Pakistan'],
        'hero_seo' => [
            'title' => 'High-Grade Zinc Ash for Recovery, Smelting and Recycling',
            'body' => 'BhattiZinc supplies 65-70% zinc ash for recyclers and smelters seeking recoverable zinc value. This zinc-rich by-product is suitable for metal recovery operations, secondary zinc production and recycling supply chains that turn galvanizing residues into usable material.',
            'highlights' => ['Zinc ash', '65-70% Zn', 'Zinc recovery', 'Secondary production'],
        ],
        'seo_blog' => [
            'title' => 'Zinc Ash Recovery: Turning Galvanizing By-Products into Value',
            'intro' => 'Zinc ash, also searched as zinc skimmings or galvanizing ash, is valuable because it contains recoverable zinc. High-grade ash can improve recovery economics for recyclers and smelters.',
            'sections' => [
                ['heading' => 'Why zinc ash has recycling value', 'body' => 'During galvanizing and zinc processing, ash forms on molten zinc surfaces. Material with 65-70% zinc content gives recovery plants a stronger zinc-bearing feedstock than lower-grade residues.'],
                ['heading' => 'Common buyers and applications', 'body' => 'Zinc ash is purchased by smelters, metal recovery plants and secondary zinc producers. It can be processed to reclaim metallic zinc or used as feedstock for zinc compounds depending on chemistry.'],
                ['heading' => 'What to check before purchase', 'body' => 'Buyers should review zinc content, moisture, contamination level, particle form, packing and shipment size. Accurate sampling is important because recovery yield depends on real composition.'],
            ],
            'faq' => [
                ['question' => 'What is zinc ash used for?', 'answer' => 'Zinc ash is mainly used for zinc recovery, recycling, smelting and secondary zinc production.'],
                ['question' => 'Is 65-70% zinc ash high grade?', 'answer' => 'Yes, 65-70% Zn is considered a strong recovery-grade material compared with lower zinc ash grades.'],
            ],
        ],
    ],
    'zinc-skimming-30-40' => [
        'meta_description' => 'Zinc skimming 30-40% Zn for large-scale zinc recovery, industrial recycling and economical smelting feedstock.',
        'seo_keywords' => ['zinc skimming', '30 40 zinc skimming', 'zinc skimming recovery', 'zinc recycling material', 'zinc skimming for smelting', 'zinc skimming supplier'],
        'hero_seo' => [
            'title' => 'Zinc Skimming for Economical Zinc Recovery Operations',
            'body' => 'BhattiZinc supplies zinc skimming with 30-40% typical zinc content for recovery plants, recyclers and smelters that process larger volumes of economical zinc-bearing feedstock. It is a practical option for industrial recycling programs focused on cost per recoverable zinc unit.',
            'highlights' => ['Zinc skimming', '30-40% Zn', 'Bulk recovery feedstock', 'Industrial recycling'],
        ],
        'seo_blog' => [
            'title' => 'How Zinc Skimming Can Work in Large-Scale  Recovery Plants',
            'intro' => 'Zinc skimming is searched by buyers who need affordable zinc-bearing material for recovery. The grade is lower than premium ash, but it can still be commercially useful when processing costs and recovery yield are balanced.',
            'sections' => [
                ['heading' => 'Best use case for 30-40% zinc skimming', 'body' => 'This material suits processors with equipment designed for bulk, lower-grade feedstock. It can support zinc recovery, industrial recycling and blending strategies where cost control matters.'],
                ['heading' => 'Why sampling is essential', 'body' => 'Lower-grade ash can vary more than refined products. Buyers should confirm zinc percentage, moisture, non-metallic content and impurities before committing to large shipments.'],
                ['heading' => 'Commercial buying context', 'body' => 'Industrial buyers often evaluate zinc skimming by zinc content, recovery route, shipment volume and landed cost. Clear material details help recovery plants compare feedstock options before committing to bulk supply.'],
            ],
            'faq' => [
                ['question' => 'Can zinc skimming be recycled?', 'answer' => 'Yes, it can be processed by suitable recovery plants and smelters to reclaim zinc value.'],
                ['question' => 'Who buys 30-40% zinc skimming?', 'answer' => 'Typical buyers include recyclers, metal recovery plants and secondary zinc processors handling bulk feedstock.'],
            ],
        ],
    ],
    'apcd-zinc-ash-50-60' => [
        'meta_description' => 'APCD zinc ash and steel mill dust 50-60% Zn for zinc recovery, recycling, metallurgical use and sustainable processing.',
        'seo_keywords' => ['APCD zinc ash', 'steel mill dust zinc', '50 60 zinc ash', 'zinc dust recovery', 'EAF dust zinc recovery', 'zinc recycling dust'],
        'hero_seo' => [
            'title' => 'APCD Zinc Ash and Steel Mill Dust for Zinc Recovery',
            'body' => 'BhattiZinc supplies APCD zinc ash containing 50-60% typical zinc for recovery and metallurgical recycling. Collected from air pollution control systems, this zinc-bearing dust helps processors recover value from industrial residues while supporting responsible waste reduction.',
            'highlights' => ['APCD zinc ash', '50-60% Zn', 'Steel mill dust', 'Zinc recovery'],
        ],
        'seo_blog' => [
            'title' => 'APCD Zinc Ash: Recovery Value in Steel Mill and Pollution Control Dust',
            'intro' => 'APCD zinc ash, steel mill dust and zinc-bearing dust are common search terms for recyclers looking for recoverable zinc. The material can be valuable when chemistry and handling requirements are understood.',
            'sections' => [
                ['heading' => 'Where APCD zinc ash comes from', 'body' => 'Air pollution control systems collect fine dust from industrial processes. When that dust contains 50-60% zinc, it becomes a meaningful feedstock for zinc recovery and metallurgical recycling.'],
                ['heading' => 'Why buyers evaluate impurities', 'body' => 'Dust materials can include chlorides, lead, iron or other elements depending on source. Recovery plants should review full analysis, not only zinc percentage, before planning processing.'],
                ['heading' => 'Sustainability and compliance', 'body' => 'Recovering zinc from APCD material can reduce landfill pressure and return valuable metal to productive use. Proper documentation and safe packing are important for transport and receiving.'],
            ],
            'faq' => [
                ['question' => 'What does APCD zinc ash mean?', 'answer' => 'APCD refers to air pollution control dust containing recoverable zinc from industrial collection systems.'],
                ['question' => 'Is steel mill dust useful for zinc recovery?', 'answer' => 'Yes, zinc-bearing steel mill dust can be processed by suitable recovery operations when its chemistry is acceptable.'],
            ],
        ],
    ],
    'zinc-dross-94-97' => [
        'meta_description' => 'Zinc dross 94-97% Zn for high-value zinc recovery, alloy production, secondary manufacturing and recycling.',
        'seo_keywords' => ['zinc dross supplier', '94 97 zinc dross', 'zinc dross recovery', 'zinc dross for alloy production', 'zinc skimmings', 'high grade zinc dross'],
        'hero_seo' => [
            'title' => 'High-Grade Zinc Dross for Recovery and Secondary Manufacturing',
            'body' => 'BhattiZinc supplies zinc dross with 94-97% typical zinc content for buyers focused on high-value recovery, alloy production and secondary manufacturing. This material is suitable for processors that need strong zinc units with practical handling and export documentation.',
            'highlights' => ['Zinc dross', '94-97% Zn', 'High-grade recovery', 'Alloy production'],
        ],
        'seo_blog' => [
            'title' => 'Zinc Dross Recovery and Why High Zinc Content Matters',
            'intro' => 'Zinc dross is often searched alongside zinc skimmings, zinc ash and secondary zinc feedstock. High-grade dross can be attractive because it contains a large percentage of recoverable zinc.',
            'sections' => [
                ['heading' => 'Dross as a zinc-rich by-product', 'body' => 'Zinc dross forms during molten zinc operations and can retain significant zinc value. Material in the 94-97% zinc range is especially useful for recovery and secondary manufacturing.'],
                ['heading' => 'Applications in alloy and remelting routes', 'body' => 'Processors may use zinc dross for reclaiming metallic zinc, alloy production or secondary zinc operations. The best route depends on physical form and impurity profile.'],
                ['heading' => 'Buying criteria for dross', 'body' => 'Ask for zinc percentage, form, sampling method, moisture, packaging and batch documents. High zinc content is important, but reliable analysis and clean handling are just as important.'],
            ],
            'faq' => [
                ['question' => 'What is zinc dross used for?', 'answer' => 'Zinc dross is used for zinc recovery, alloy production and secondary manufacturing.'],
                ['question' => 'Is zinc dross the same as zinc ash?', 'answer' => 'They are related zinc-bearing by-products, but form, zinc percentage and processing behavior can differ by source.'],
            ],
        ],
    ],
    'zinc-die-cast-scrap' => [
        'meta_description' => 'Zinc die cast scrap for recycling, remelting, secondary zinc production and circular metal supply chains.',
        'seo_keywords' => ['zinc die cast scrap', 'zamak scrap', 'zinc scrap supplier', 'die casting scrap recycling', 'zinc remelting scrap', 'secondary zinc scrap'],
        'hero_seo' => [
            'title' => 'Zinc Die Cast Scrap for Recycling, Remelting and Secondary Production',
            'body' => 'BhattiZinc supplies zinc die cast scrap for recyclers, smelters and secondary producers seeking sorted zinc-bearing material. It is used for remelting, recycling and secondary zinc production where prepared scrap quality directly affects recovery value and melt consistency.',
            'highlights' => ['Zinc die cast scrap', 'Remelting', 'Secondary production', 'Recycling'],
        ],
        'seo_blog' => [
            'title' => 'Zinc Die Cast Scrap Recycling for Secondary Zinc Production',
            'intro' => 'Searches for zinc die cast scrap, zamak scrap and zinc remelting scrap usually come from buyers who need recyclable zinc units. Sorting and source quality determine how useful the scrap will be in production.',
            'sections' => [
                ['heading' => 'Why die cast scrap is recyclable', 'body' => 'Many zinc die cast parts and trims can be remelted or processed for secondary production. Prepared scrap helps keep zinc in circulation and supports lower-cost metal supply.'],
                ['heading' => 'Common industrial buyers', 'body' => 'Smelters, scrap processors, foundries and secondary zinc producers buy die cast scrap for remelting and blending. Clean sorting improves predictability and reduces processing loss.'],
                ['heading' => 'What affects scrap value', 'body' => 'Value depends on alloy type, contamination, attachments, moisture, sorting quality and market demand. Buyers should request photos, grade details and shipment terms before purchase.'],
            ],
            'faq' => [
                ['question' => 'Can zinc die cast scrap be remelted?', 'answer' => 'Yes, suitable zinc die cast scrap can be recycled, remelted or processed for secondary zinc production.'],
                ['question' => 'What is zamak scrap?', 'answer' => 'Zamak scrap is zinc alloy scrap from die-cast components that often contains aluminum, magnesium and copper additions.'],
            ],
        ],
    ],
];

foreach ($products as &$product) {
    if (isset($productSeoContent[$product['slug']])) {
        $product = array_merge($product, $productSeoContent[$product['slug']]);
    }
}
unset($product);

function getProductBySlug($slug, $products) {
    foreach ($products as $product) {
        if ($product['slug'] === $slug) return $product;
    }
    return null;
}

function getFeaturedProducts($products) {
    return array_filter($products, fn($p) => $p['featured']);
}

function getHeroProducts($products) {
    $hero = array_filter($products, fn($p) => isset($p['hero_order']) && $p['hero_order'] > 0);
    usort($hero, fn($a, $b) => $a['hero_order'] - $b['hero_order']);
    return $hero;
}

function getProductsByCategory($category, $products) {
    return array_filter($products, fn($p) => $p['category'] === $category);
}
?>
